apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring1
  name: spring1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring1
    spec:
      containers:
        - image: pzombade/spring-boot-docker
          name: spring-boot-docker
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: from
              value: k8s
status: {}