apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring1
  name: spring1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring1
    spec:
      containers:
        - image: pzombade/spring-boot-docker
          name: spring-boot-docker
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: from
              value: k8s
status: {}
---

apiVersion: v1
kind: Service
metadata:
  name: spring1
spec:
  type: NodePort
  selector:
    app: spring1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001